name: Maven Package

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=stephen-t-kaye
          -Dsonar.projectKey=callisto-jparest
          -Dsonar.projectName=callisto-jparest
          -Dsonar.qualitygate.wait=true
          -Dsonar.verbose=true
